# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: cleanarchitecture

extensions:
- name: seq
  logPath: ./.logs

services:

- name: webapi
  project: src/Presentation/WebApi/WebApi.csproj
  bindings:
  - port: 5001
    name: https
    protocol: https
  - port: 5000
    name: http
    protocol: http
  replicas: 1
  env:
  - name: UseInMemoryDatabase
    value: false
  - name: RunEFCoreMigrations
    value: true
  - name: ConnectionStrings__DefaultConnection
    value: Server=host.docker.internal,1433;database=CleanArchitectureDb;User Id=sa;Password=Password_123;
  - name: DataProtectionKeysConfig__Enabled
    value: true
  - name: DataProtectionKeysConfig__RedisServer
    value: host.docker.internal,6379
  - name: OpenTelemetryConfig__Enabled
    value: true
  - name: OpenTelemetryConfig__JaegerExporter__AgentHost
    value: localhost
  - name: OpenTelemetryConfig__JaegerExporter__AgentPort
    value: 6831
  - name: Serilog__WriteTo__1__Name
    value: LokiHttp
  - name: Serilog__WriteTo__1__Args__serverUrl
    value: http://localhost:3100
  - name: Serilog__WriteTo__2__Name
    value: Seq
  - name: Serilog__WriteTo__2__Args__serverUrl
    value: http://host.docker.internal:5341

- name: webapi-db
  image: mcr.microsoft.com/mssql/server
  env:
  - name: ACCEPT_EULA
    value: Y
  - name: SA_PASSWORD
    value: Password_123
  volumes:
  - name: webapi-db-storage
    target: /var/opt/mssql
  bindings:
  - port: 1433
    connectionString: Server=${host}:${port};Database=CleanArchitectureDb;MultipleActiveResultSets=true;User Id=sa;Password=${env:SA_PASSWORD}

- name: redis
  image: redis
  bindings:
  - port: 6379
  volumes:
  - name: webapi-redis-storage
    target: /data

- name: redis-commander
  image: rediscommander/redis-commander:latest
  bindings:
  - port: 8081
    protocol: http
  env:
  - name: REDIS_HOSTS
    value: local:redis:6379
  - name: HTTP_USER
    value: root
  - name: HTTP_USER
    value: Password_123

- name: loki
  image: grafana/loki
  bindings:
  - port: 3100
    containerPort: 3100
    protocol: http
  volumes:
  - name: webapi-loki-storage
    target: /loki

- name: grafana
  image: grafana/grafana
  bindings:
  - port: 3000
    containerPort: 3000
    protocol: http
  env:
  - name: GF_INSTALL_PLUGINS
    value: grafana-piechart-panel
  volumes:
  - name: webapi-grafana-storage
    target: /var/lib/grafana

- name: jaeger
  image: jaegertracing/all-in-one:1.24
  env:
  - name: COLLECTOR_ZIPKIN_HTTP_PORT
    value: 9411
  bindings:
  - port: 16686
    containerPort: 16686
    name: jaeger-ui
    protocol: http
  - port: 6831
    containerPort: 6831
    name: jaeger-receiver
    protocol: udp

- name: prometheus
  image: prom/prometheus
  bindings:
  - port: 9090
    containerPort: 9090
    protocol: http
  volumes:
  - name: prometheus-configmap
    source: ./prometheus
    target: /etc/prometheus
